version: '3.4'

networks:
  remotely:
    name: remotely-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1

services:
  remotely:
    image: immybot/remotely:latest
    container_name: remotely
    volumes:
      - /var/www/remotely:/app/AppData
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - remotely
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      # Force only HTTP, disable HTTPS
      - ASPNETCORE_URLS=http://+:5000

      # Logging overrides
      - Serilog__MinimumLevel__Override__Microsoft.AspNetCore=Warning
      - Serilog__MinimumLevel__Override__System=Warning

      # Database provider
      - Remotely_ApplicationOptions__DbProvider=SQLite
      - Remotely_ApplicationOptions__DockerGateway=172.28.0.1
      - Remotely_ConnectionStrings__SQLite=Data Source=/app/AppData/Remotely.db
      - Remotely_ConnectionStrings__SQLServer=Server=(localdb)\\mssqllocaldb;Database=Remotely-Server;Trusted_Connection=True;MultipleActiveResultSets=true
      - Remotely_ConnectionStrings__PostgreSQL=Host=localhost;Database=Remotely;Username=postgres;Password=changeme;
